[build]
  base = "basic_banking_system-main"
  command = "npm install && npm run build"
  publish = "."
  functions = "functions"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"