[build]
  base = "basic_banking_system-main"
  command = "npm install && mkdir -p functions && cp index.js functions/server.js"
  publish = "."
  functions = "functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["views/**", "router/**", "models/**"]

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server"

[build.environment]
  NODE_VERSION = "16"